Выполнен 3 модуль
js-tasks-ru/jsbasic-20220519_yaphetsoo pull request #4
Opened 2022-05-31 13:58 UTC by cryptoh4mster

2022-05-31 13:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-31 20:17 UTC, SinimaWath requested changes

2022-05-31 20:17 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  });
Это очень похоже на связку: filter -> map

2022-05-31 21:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-05-31 21:06 UTC, cryptoh4mster commented on 3-module/5-task/index.js
> +  });
Исправил

2022-06-01 20:25 UTC, SinimaWath approved these changes

2022-06-01 20:26 UTC, merged